git mv clisp/Dockerfile clisp.Dockerfile
git mv afterthedeadline/Dockerfile afterthedeadline.Dockerfile
git mv irssi/Dockerfile irssi.Dockerfile
git mv powershell-azure/Dockerfile powershell-azure.Dockerfile
git mv httpie/Dockerfile httpie.Dockerfile
git mv azure-cli/Dockerfile azure-cli.Dockerfile
git mv remmina/Dockerfile remmina.Dockerfile
git mv zookeeper/3.4/Dockerfile zookeeper-3.4.Dockerfile
git mv zookeeper/3.5/Dockerfile zookeeper-3.5.Dockerfile
git mv perkeep/Dockerfile perkeep.Dockerfile
git mv tor-router/Dockerfile tor-router.Dockerfile
git mv debootstrap/Dockerfile debootstrap.Dockerfile
git mv clair/Dockerfile clair.Dockerfile
git mv cathode/Dockerfile cathode.Dockerfile
git mv texlive/Dockerfile texlive.Dockerfile
git mv virt-viewer/Dockerfile virt-viewer.Dockerfile
git mv notify-osd/Dockerfile notify-osd.Dockerfile
git mv shellcheck/Dockerfile shellcheck.Dockerfile
git mv clean-registry/Dockerfile clean-registry.Dockerfile
git mv nmap/Dockerfile nmap.Dockerfile
git mv slapd/Dockerfile slapd.Dockerfile
git mv packer/Dockerfile packer.Dockerfile
git mv imagemin/Dockerfile imagemin.Dockerfile
git mv iceweasel/Dockerfile iceweasel.Dockerfile
git mv evince/Dockerfile evince.Dockerfile
git mv wargames/Dockerfile wargames.Dockerfile
git mv freeradius/Dockerfile freeradius.Dockerfile
git mv certbot/Dockerfile certbot.Dockerfile
git mv chrome/stable/Dockerfile chrome-stable.Dockerfile
git mv chrome/beta/Dockerfile chrome-beta.Dockerfile
git mv android-tools/Dockerfile android-tools.Dockerfile
git mv inkscape/Dockerfile inkscape.Dockerfile
git mv tor-proxy/Dockerfile tor-proxy.Dockerfile
git mv gmail-britta/Dockerfile gmail-britta.Dockerfile
git mv fontpatcher/Dockerfile fontpatcher.Dockerfile
git mv curl/Dockerfile curl.Dockerfile
git mv wireguard/install/Dockerfile wireguard-install.Dockerfile
git mv wireguard/tools/Dockerfile wireguard-tools.Dockerfile
git mv pandoc/Dockerfile pandoc.Dockerfile
git mv transfer-sh/Dockerfile transfer-sh.Dockerfile
git mv skype/Dockerfile skype.Dockerfile
git mv requestbin/Dockerfile requestbin.Dockerfile
git mv shorewall/Dockerfile shorewall.Dockerfile
git mv httpbin/Dockerfile httpbin.Dockerfile
git mv guetzli/Dockerfile guetzli.Dockerfile
git mv mc/Dockerfile mc.Dockerfile
git mv plexpy/Dockerfile plexpy.Dockerfile
git mv geary/Dockerfile geary.Dockerfile
git mv htpasswd/Dockerfile htpasswd.Dockerfile
git mv apt-file/Dockerfile apt-file.Dockerfile
git mv gixy/Dockerfile gixy.Dockerfile
git mv transmission-ui/Dockerfile transmission-ui.Dockerfile
git mv cli53/Dockerfile cli53.Dockerfile
git mv buttslock/Dockerfile buttslock.Dockerfile
git mv lpass/Dockerfile lpass.Dockerfile
git mv powershell/Dockerfile powershell.Dockerfile
git mv libvirt-client/Dockerfile libvirt-client.Dockerfile
git mv fontforge/Dockerfile fontforge.Dockerfile
git mv audacity/Dockerfile audacity.Dockerfile
git mv lilyterm/Dockerfile lilyterm.Dockerfile
git mv mop/Dockerfile mop.Dockerfile
git mv pivman/Dockerfile pivman.Dockerfile
git mv doctor/Dockerfile doctor.Dockerfile
git mv netcat/Dockerfile netcat.Dockerfile
git mv cheese/Dockerfile cheese.Dockerfile
git mv virtualbox/Dockerfile virtualbox.Dockerfile
git mv registry-auth/Dockerfile registry-auth.Dockerfile
git mv ghostscript/Dockerfile ghostscript.Dockerfile
git mv k8scan/Dockerfile k8scan.Dockerfile
git mv dunnet/Dockerfile dunnet.Dockerfile
git mv sublime-text-3/Dockerfile sublime-text-3.Dockerfile
git mv awscli/Dockerfile awscli.Dockerfile
git mv tor-relay/Dockerfile tor-relay.Dockerfile
git mv imagemagick/Dockerfile imagemagick.Dockerfile
git mv transmission/Dockerfile transmission.Dockerfile
git mv runc-rootless/Dockerfile runc-rootless.Dockerfile
git mv rdesktop/Dockerfile rdesktop.Dockerfile
git mv wrk/Dockerfile wrk.Dockerfile
git mv bcc-tools/Dockerfile bcc-tools.Dockerfile
git mv termboy/Dockerfile termboy.Dockerfile
git mv now/Dockerfile now.Dockerfile
git mv stress/Dockerfile stress.Dockerfile
git mv vlc/Dockerfile vlc.Dockerfile
git mv parrot-live/Dockerfile parrot-live.Dockerfile
git mv strace/Dockerfile strace.Dockerfile
git mv zoom-us/Dockerfile zoom-us.Dockerfile
git mv pms/Dockerfile pms.Dockerfile
git mv coredns/Dockerfile coredns.Dockerfile
git mv wee-slack/Dockerfile wee-slack.Dockerfile
git mv gparted/Dockerfile gparted.Dockerfile
git mv hollywood/Dockerfile hollywood.Dockerfile
git mv john/Dockerfile john.Dockerfile
git mv wine/Dockerfile wine.Dockerfile
git mv openvpn/Dockerfile openvpn.Dockerfile
git mv fleet/Dockerfile fleet.Dockerfile
git mv nomad/Dockerfile nomad.Dockerfile
git mv ricochet/Dockerfile ricochet.Dockerfile
git mv linapple/Dockerfile linapple.Dockerfile
git mv mpsyt/Dockerfile mpsyt.Dockerfile
git mv t/Dockerfile t.Dockerfile
git mv jq/Dockerfile jq.Dockerfile
git mv wireshark/Dockerfile wireshark.Dockerfile
git mv tarsnap/Dockerfile tarsnap.Dockerfile
git mv foss-heartbeat/Dockerfile foss-heartbeat.Dockerfile
git mv ab/Dockerfile ab.Dockerfile
git mv terraform/Dockerfile terraform.Dockerfile
git mv radarr/Dockerfile radarr.Dockerfile
git mv dcos-cli/Dockerfile dcos-cli.Dockerfile
git mv github-dev/Dockerfile github-dev.Dockerfile
git mv scudcloud/Dockerfile scudcloud.Dockerfile
git mv gitiles/Dockerfile gitiles.Dockerfile
git mv cfssl/Dockerfile cfssl.Dockerfile
git mv neoman/Dockerfile neoman.Dockerfile
git mv privoxy/Dockerfile privoxy.Dockerfile
git mv gcc/Dockerfile gcc.Dockerfile
git mv checkup/Dockerfile checkup.Dockerfile
git mv znc/Dockerfile znc.Dockerfile
git mv gnuplot/Dockerfile gnuplot.Dockerfile
git mv rt-tests/Dockerfile rt-tests.Dockerfile
git mv rainbowstream/Dockerfile rainbowstream.Dockerfile
git mv vagrant/Dockerfile vagrant.Dockerfile
git mv rstudio/Dockerfile rstudio.Dockerfile
git mv unifi/Dockerfile unifi.Dockerfile
git mv postfix/Dockerfile postfix.Dockerfile
git mv kvm/Dockerfile kvm.Dockerfile
git mv protocol/Dockerfile protocol.Dockerfile
git mv weechat/Dockerfile weechat.Dockerfile
git mv gitsome/Dockerfile gitsome.Dockerfile
git mv sickbeard/Dockerfile sickbeard.Dockerfile
git mv atom/Dockerfile atom.Dockerfile
git mv micro/Dockerfile micro.Dockerfile
git mv mailman/Dockerfile mailman.Dockerfile
git mv plex-home-theater/Dockerfile plex-home-theater.Dockerfile
git mv ansible/Dockerfile ansible.Dockerfile
git mv mitmproxy/Dockerfile mitmproxy.Dockerfile
git mv distcc/Dockerfile distcc.Dockerfile
git mv keepass2/Dockerfile keepass2.Dockerfile
git mv pop/Dockerfile pop.Dockerfile
git mv viewdocs/Dockerfile viewdocs.Dockerfile
git mv ncmpc/Dockerfile ncmpc.Dockerfile
git mv zsh/Dockerfile zsh.Dockerfile
git mv mpd/Dockerfile mpd.Dockerfile
git mv telize/Dockerfile telize.Dockerfile
git mv pond/Dockerfile pond.Dockerfile
git mv mdp/Dockerfile mdp.Dockerfile
git mv gcloud/Dockerfile gcloud.Dockerfile
git mv osquery/Dockerfile osquery.Dockerfile
git mv vault/Dockerfile vault.Dockerfile
git mv telnet/Dockerfile telnet.Dockerfile
git mv spotify/Dockerfile spotify.Dockerfile
git mv couchpotato/Dockerfile couchpotato.Dockerfile
git mv mars/Dockerfile mars.Dockerfile
git mv htop/Dockerfile htop.Dockerfile
git mv lynx/Dockerfile lynx.Dockerfile
git mv nzbget/Dockerfile nzbget.Dockerfile
git mv slack/Dockerfile slack.Dockerfile
git mv masscan/Dockerfile masscan.Dockerfile
git mv glxgears/Dockerfile glxgears.Dockerfile
git mv spotify-wine/Dockerfile spotify-wine.Dockerfile
git mv sonarr/Dockerfile sonarr.Dockerfile
git mv firefox/Dockerfile firefox.Dockerfile
git mv firefox/alpine/Dockerfile firefox-alpine.Dockerfile
git mv routersploit/Dockerfile routersploit.Dockerfile
git mv watchtower/Dockerfile watchtower.Dockerfile
git mv kernel-builder/Dockerfile kernel-builder.Dockerfile
git mv travis/Dockerfile travis.Dockerfile
git mv oauth2-proxy/Dockerfile oauth2-proxy.Dockerfile
git mv metasploit/Dockerfile metasploit.Dockerfile
git mv yubico-piv-tool/Dockerfile yubico-piv-tool.Dockerfile
git mv gimp/Dockerfile gimp.Dockerfile
git mv pdp-10/its/Dockerfile pdp-10-its.Dockerfile
git mv keepassxc/Dockerfile keepassxc.Dockerfile
git mv traceroute/Dockerfile traceroute.Dockerfile
git mv libreoffice/Dockerfile libreoffice.Dockerfile
git mv consul/Dockerfile consul.Dockerfile
git mv tetris/Dockerfile tetris.Dockerfile
git mv pulseaudio/Dockerfile pulseaudio.Dockerfile
git mv lkp-tests/Dockerfile lkp-tests.Dockerfile
git mv node-sonos/Dockerfile node-sonos.Dockerfile
git mv nes/Dockerfile nes.Dockerfile
git mv troff/Dockerfile troff.Dockerfile
git mv beeswithmachineguns/Dockerfile beeswithmachineguns.Dockerfile
git mv mailgun/Dockerfile mailgun.Dockerfile
git mv no_new_privs/Dockerfile no_new_privs.Dockerfile
git mv gitserver/Dockerfile gitserver.Dockerfile
git mv nerdy/Dockerfile nerdy.Dockerfile
git mv ykpersonalize/Dockerfile ykpersonalize.Dockerfile
git mv s3cmd/Dockerfile s3cmd.Dockerfile
git mv unixbench/Dockerfile unixbench.Dockerfile
git mv gcalcli/Dockerfile gcalcli.Dockerfile
git mv cloudapp/Dockerfile cloudapp.Dockerfile
git mv ykman/Dockerfile ykman.Dockerfile
git mv tor-browser/stable/Dockerfile tor-browser-stable.Dockerfile
git mv tor-browser/alpha/Dockerfile tor-browser-alpha.Dockerfile
git mv browsh/Dockerfile browsh.Dockerfile
git mv nginx-extras/Dockerfile nginx-extras.Dockerfile
git mv vscode/Dockerfile vscode.Dockerfile
git mv cf-reset-cache/Dockerfile cf-reset-cache.Dockerfile
git mv chromium/Dockerfile chromium.Dockerfile
git mv mutt/Dockerfile mutt.Dockerfile